version: '3.2'

services:

  # mosquitto broker
  emqx:
    image: "emqx/emqx:latest"
    #image: "eclipse-mosquitto:1.6.4"
    network_mode: "host"
    ports:
      - "8888:8888"
      - "8889:8889"
    #privileged: true
    environment:
      - EMQX_LISTENER__WS__EXTERNAL=8888
      - EMQX_LISTENER__TCP__EXTERNAL=8889
    # - EMQX_HOST=127.0.0.1
      - EMQX_MQTT__MAX_PACKET_SIZE=10240KB
