version: '3.2'

services:

  # mosquitto broker
  mosquitto:
    image: "eclipse-mosquitto:1.6.4"
    network_mode: "host"
    ports:
      - "1883:1883"
      - "1884:1884"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf